

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ActivitiesApp
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class ActivitiesAppEntities : DbContext
{

    private static ActivitiesAppEntities instance;

    public static ActivitiesAppEntities GetInstance()
    {
        if (instance == null)
            {
                instance = new ActivitiesAppEntities();
            }
        return instance;
    }

    public ActivitiesAppEntities()
        : base("name=ActivitiesAppEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Cтраны> Cтраны { get; set; }

    public virtual DbSet<Активности> Активности { get; set; }

    public virtual DbSet<Города> Города { get; set; }

    public virtual DbSet<Мероприятия> Мероприятия { get; set; }

    public virtual DbSet<Пол> Пол { get; set; }

    public virtual DbSet<Пользователи> Пользователи { get; set; }

    public virtual DbSet<Роли> Роли { get; set; }

}

}

