
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ActivitiesApp
{

using System;
    using System.Collections.Generic;
    
public partial class Активности
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Активности()
    {

        this.Пользователи = new HashSet<Пользователи>();

    }


    public int ID { get; set; }

    public int EventID { get; set; }

    public string Name { get; set; }

    public int Day { get; set; }

    public System.TimeSpan StartTime { get; set; }

    public int Moderator { get; set; }



    public virtual Мероприятия Мероприятия { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Пользователи> Пользователи { get; set; }

}

}
